FROM nginx:latest

RUN apt-get update && apt-get install -y cron python git wget
ADD scripts/get_cert_cron /get_cert_cron
RUN crontab /get_cert_cron
CMD /bin/bash -c "service cron start && nginx -g 'daemon off;'"
