FROM nginx:latest

RUN apt-get update && apt-get install -y cron python git wget
ADD scripts/get_cert_cron /get_cert_cron
RUN crontab /get_cert_cron
RUN git clone https://github.com/diafygi/acme-tiny.git /opt/acme-tiny
CMD /bin/bash -c "service cron start && chmod 600 /etc/nginx/nginx.key /etc/nginx/nginx.crt && nginx -g 'daemon off;'"
